### ISSUE TITLE
unable to run the v0.0.7 with docker through local network

### ISSUE THREAD

**Issue by purplenut** [stackblitz-labs/bolt.diy#1430]
### Describe the bug

hey guys i've tried to update from 0.0.6 to 0.0.7 today. 
i've ran into a couple of issues
first here is what i've used in my docker compose file:
```
services:
 bolt.diy:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    ports:
      - "5173:5173"
    env_file: .env
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
     # - NODE_ENV=development
     # - VITE_HMR_PROTOCOL=ws
     # - VITE_HMR_HOST=localhost
     # - VITE_HMR_PORT=5173
     # - CHOKIDAR_USEPOLLING=true
     # - WATCHPACK_POLLING=true
      - PORT=5173
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./project:/home/project
    command: pnpm run dockerstart
    networks:
      - ollama_default

networks:
  ollama_default:
    external: true
```

at first this did not work i've got an error about enable to build
but i've looked around the open issues and changed pnpm run dockerstart to run dev -host 0.0.0.0
thats when i added the commented VITE lines above
i also tried this:
```
      #- VITE_HMR_PROTOCOL=wss
      #- VITE_HMR_HOST=bolt.local.domain.com
      #- VITE_HMR_PORT=443
      #- CHOKIDAR_USEPOLLING=true
      #- WATCHPACK_POLLING=true
```

the issue i am trying to resolve is to access bolt.diy from my local network
my current setup is i am using traefik to get HTTPS and the cors headers for bolt diy to work
by using run dev i was able to access bolt.diy at local-IP:5173 but when i visit bolt.local.domain.com the page loads forever without an error code.
my traefik setup is the same as it was working for the version 0.0.6 

for now i downgraded to:
ghcr.io/stackblitz-labs/bolt.diy:6a8449e
and this is currently working with pnpm run dockerstart

### Link to the Bolt URL that caused the error

https://github.com/stackblitz-labs/bolt.diy/releases/tag/v0.0.7

### Steps to reproduce

update compose file to 0.0.7
use pnpm run dockerstart 
get an error
use pnpm run dev -host 0.0.0.0
visit the bolt.diy proxied domain name
the page loads forever without throwing an error

### Expected behavior

page loads with SSL certificate and cors headers from traefik 

### Platform

- OS: [e.g. debian 12, Docker]
- Browser: [e.g. Chrome, Firefox]
- Version: [e.g. 91.1]
